#!/bin/sh

mknod -m 0666 /dev/null c 1 3
mknod -m 0660 /dev/ttyS0 c 4 64

mount -t proc proc /proc
mount -t sysfs sysfs /sys

/sbin/insmod /lib/modules/keml.ko
mknod /dev/keml c 414 0
chmod a+rw /dev/keml

mv flag root
chown root:root root/flag
chmod 660 root/flag

cat <<!
Boot took $(cut -d' ' -f1 /proc/uptime) seconds
!

setsid cttyhack setuidgid 1000 /bin/sh

umount /proc
umount /sys

poweroff -f
