#!/bin/sh

mknod -m 0666 /dev/null c 1 3
mknod -m 0660 /dev/ttyS0 c 4 64
mknod -m 622 /dev/console c 5 1
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0
mknod -m 444 /dev/random c 1 8
mknod -m 444 /dev/urandom c 1 9
chown -v root:tty /dev/{console,ptmx,tty}
mknod /dev/loop0 b 7 0


/sbin/insmod /lib/modules/dmyfs.ko

mv flag root
chown root:root root/flag
chmod 660 root/flag
mkdir /tmp
mkdir /mnt
mkdir /mnt/PWN

mkdir /proc
mkdir /sys
mount -t proc proc /proc
mount -t sysfs sysfs /sys

chown root:root /do_mount
chown root:root /do_unmount
chmod u+s /do_mount
chmod g+s /do_mount
chmod u+s /do_unmount
chmod g+s /do_unmount
chmod -R 777 /tmp

cat <<!
Boot took $(cut -d' ' -f1 /proc/uptime) seconds
welcome...
!

cat /proc/kallsyms > /tmp/kallsyms
chmod 777 /tmp/kallsyms

mkdir  -p /dev/pts

mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null \
	        || mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev

[ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || mkdir -m 755 /dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts
# shared memory area (later system will need it)
[ -d /dev/shm ] || mkdir /dev/shm
mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

setsid cttyhack setuidgid 1000 /bin/sh

poweroff -f
